### ISSUE TITLE
What's the license of this project?

### ISSUE THREAD

**Issue by liach** [Mumfrey/ClientPermissionsLib#1]

**Comment by Mumfrey** [comment]
None currently.

**Comment by liach** [comment]
Well I asked this just because this seems to be included in both Almura and Liteloader, both All rights reserved. Thanks.

**Comment by Mumfrey** [comment]
This serves as a reference implementation for the payload class. The class can simply by used in its compiled form if you wish to make projects which interact with ClientPermissions without using the published implementations.
